[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'ffmpeg']

[phases.install]
cmds = ['npm ci --prefix server']

[phases.build]
cmds = ['npm run build --prefix server']

[start]
cmd = 'node server/dist/index.js'

[variables]
YOUTUBE_DL_SKIP_PYTHON_CHECK = '1'
