[phases.setup]
nixPkgs = ['nodejs_20', 'ffmpeg']

[phases.install]
cmds = ['npm ci --prefix server']

[phases.build]
cmds = ['npm run build --prefix server']

[start]
cmd = 'node server/dist/index.js'
