# Cache bust: 2025-10-07 (FFmpeg removed - using yt-dlp pre-merged formats)
[phases.setup]
nixPkgs = ['nodejs_20', 'python3']

[phases.install]
cmds = ['npm ci --prefix server --ignore-scripts']

[phases.build]
cmds = ['echo "Build 2025-10-07" && npm ci --prefix server && npm run build --prefix server']

[start]
cmd = 'node server/dist/index.js'

[variables]
YOUTUBE_DL_SKIP_PYTHON_CHECK = '1'
