name: Production Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run smoke tests against production
        shell: pwsh
        run: ./tools/smoke-prod.ps1
